### ISSUE TITLE
Improve navbar styling

### ISSUE THREAD

**Issue by ModeratelyGreek** [UF-GDA/Feedback#62] opened 2022-08-06 00:22 UTC
The login options need to hide itself, and not all links disappear when the hamburger menu is triggered. Playing with the sizing here for a more professional look will hopefully yield better results.

**Comment by Exanite** [comment] 2022-08-06 00:22
> not all links disappear when the hamburger menu is triggered

This is 100% intentional since I want to fit as many links on the screen as possible.
![image](https://user-images.githubusercontent.com/42710136/183226031-8f71d804-d3a0-4e11-9523-b594dacd30f9.png)

**Comment by ModeratelyGreek** [comment] 2022-08-06 00:23
Understood but I think we can improve the feel of this on smaller screens just a bit

**Comment by Exanite** [comment] 2022-08-14 19:53
Since all current functionality is as intended, this has been marked as an enhancement instead

**Closed as not planned** 2023-04-07 23:34 UTC
Labels: Enhancement, Question, Website, Consider Closing
